In [17]:
import sys

from sympy.stats.sampling.sample_numpy import numpy
from triton.language import device_print

assert sys.version_info>=(3,10)


In [21]:
import torch
import matplotlib.pyplot as plt


In [57]:
X=torch.tensor([[20.0,30,59],[-1,232,3]])
X

tensor([[ 20.,  30.,  59.],
        [ -1., 232.,   3.]])

In [33]:
X.shape

torch.Size([2, 3])

In [34]:
X.dtype

torch.float32

In [35]:
X[0,1]

tensor(30.)

In [36]:
X.mean()


tensor(19.1667)

In [40]:
X.max(dim=0)

torch.return_types.max(
values=tensor([ 20., 232.,  59.]),
indices=tensor([0, 1, 0]))

In [41]:
X@X.T

tensor([[ 4781.,  7157.],
        [ 7157., 53834.]])

In [46]:
import numpy as np
print(X.numpy())


[[ 20.  30.  59.]
 [  1. 232.   3.]]


In [50]:
X.tolist()

[[20.0, 30.0, 59.0], [1.0, 232.0, 3.0]]

In [54]:
X2=torch.from_numpy(X.numpy())
X2[1,0]=6654656
X

tensor([[2.0000e+01, 3.0000e+01, 5.9000e+01],
        [6.6547e+06, 2.3200e+02, 3.0000e+00]])

In [58]:
X.relu_()

tensor([[ 20.,  30.,  59.],
        [  0., 232.,   3.]])

In [67]:
function=lambda mod:set(f for f in dir(mod) if callable(getattr(mod,f)))
", ".join(sorted(function(torch)&function(np)))


'__getattr__, abs, absolute, acos, acosh, add, all, allclose, amax, amin, angle, any, arange, arccos, arccosh, arcsin, arcsinh, arctan, arctan2, arctanh, argmax, argmin, argsort, argwhere, asarray, asin, asinh, atan, atan2, atanh, atleast_1d, atleast_2d, atleast_3d, bincount, bitwise_and, bitwise_left_shift, bitwise_not, bitwise_or, bitwise_right_shift, bitwise_xor, broadcast_shapes, broadcast_to, can_cast, ceil, clip, column_stack, concat, concatenate, conj, copysign, corrcoef, cos, cosh, count_nonzero, cov, cross, cumprod, cumsum, deg2rad, diag, diagflat, diagonal, diff, divide, dot, dsplit, dstack, dtype, einsum, empty, empty_like, equal, exp, exp2, expm1, eye, finfo, fix, flip, fliplr, flipud, float_power, floor, floor_divide, fmax, fmin, fmod, frexp, from_dlpack, frombuffer, full, full_like, gcd, gradient, greater, greater_equal, heaviside, histogram, histogramdd, hsplit, hstack, hypot, i0, iinfo, imag, inner, isclose, isfinite, isin, isinf, isnan, isneginf, isposinf, isreal, kron

In [70]:
print(device)

NameError: name 'device' is not defined

In [72]:
if torch.cuda.is_available():
    device="cuda"
elif torch.backends.mps.is_available()
    device="mps"
else :
    device="cpu"
device

SyntaxError: expected ':' (3524568285.py, line 3)